"""add equipment_post_ids

Revision ID: 10d036b22ff7
Revises: 15a4e7bebcb7
Create Date: 2026-03-26 16:01:41.734892

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '10d036b22ff7'
down_revision: str | Sequence[str] | None = '15a4e7bebcb7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _table_has_column(table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return any(column["name"] == column_name for column in inspector.get_columns(table_name))


def _table_has_index(table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return any(index["name"] == index_name for index in inspector.get_indexes(table_name))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE attendance_log SET timestamp = now() WHERE timestamp IS NULL")
    op.execute("UPDATE bookings SET is_weekly = false WHERE is_weekly IS NULL")
    op.execute("UPDATE bookings SET created_at = now() WHERE created_at IS NULL")
    op.execute("UPDATE swap_offers SET status = 'pending' WHERE status IS NULL")
    op.execute("UPDATE swap_offers SET created_at = now() WHERE created_at IS NULL")
    op.execute("UPDATE users SET warnings = 0 WHERE warnings IS NULL")
    op.execute("UPDATE users SET banned = false WHERE banned IS NULL")

    op.alter_column('attendance_log', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'is_weekly',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('equipment_request_ranges', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('equipment_requests', sa.Column('equipment_post_chat_id', sa.BigInteger(), nullable=True))
    op.add_column('equipment_requests', sa.Column('equipment_post_message_id', sa.Integer(), nullable=True))
    if _table_has_index('equipment_requests', 'ix_equipment_requests_needed_at'):
        op.drop_index(op.f('ix_equipment_requests_needed_at'), table_name='equipment_requests')
    if _table_has_column('equipment_requests', 'needed_at'):
        op.drop_column('equipment_requests', 'needed_at')
    op.alter_column('swap_offers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('swap_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_swap_offers_give_slot', 'swap_offers', ['give_date', 'give_hour'], unique=False)
    op.create_index('ix_swap_offers_giver_user_id', 'swap_offers', ['giver_user_id'], unique=False)
    op.create_index('ix_swap_offers_receiver_user_id', 'swap_offers', ['receiver_user_id'], unique=False)
    op.create_index('ix_swap_offers_want_slot', 'swap_offers', ['want_date', 'want_hour'], unique=False)
    op.create_foreign_key('fk_swap_offers_receiver', 'swap_offers', 'users', ['receiver_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_swap_offers_giver', 'swap_offers', 'users', ['giver_user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'warnings',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'warnings',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.drop_constraint('fk_swap_offers_receiver', 'swap_offers', type_='foreignkey')
    op.drop_constraint('fk_swap_offers_giver', 'swap_offers', type_='foreignkey')
    op.drop_index('ix_swap_offers_want_slot', table_name='swap_offers')
    op.drop_index('ix_swap_offers_receiver_user_id', table_name='swap_offers')
    op.drop_index('ix_swap_offers_giver_user_id', table_name='swap_offers')
    op.drop_index('ix_swap_offers_give_slot', table_name='swap_offers')
    op.alter_column('swap_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('swap_offers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('equipment_requests', sa.Column('needed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_equipment_requests_needed_at'), 'equipment_requests', ['needed_at'], unique=False)
    op.drop_column('equipment_requests', 'equipment_post_message_id')
    op.drop_column('equipment_requests', 'equipment_post_chat_id')
    op.alter_column('equipment_request_ranges', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'is_weekly',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('attendance_log', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
