"""add swap_request

Revision ID: 19ba4c4bc7e6
Revises: e060b471efb4
Create Date: 2025-11-28 11:54:27.507169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19ba4c4bc7e6'
down_revision: Union[str, Sequence[str], None] = 'e060b471efb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swap_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giver_user_id', sa.Integer(), nullable=False),
    sa.Column('receiver_user_id', sa.Integer(), nullable=False),
    sa.Column('give_date', sa.Date(), nullable=False),
    sa.Column('give_hour', sa.Integer(), nullable=False),
    sa.Column('want_date', sa.Date(), nullable=False),
    sa.Column('want_hour', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('swap_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swap_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('swap_requests_requester_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('swap_requests_pkey'))
    )
    op.drop_table('swap_offers')
    # ### end Alembic commands ###
