"""warnings_system

Revision ID: 3cce9839893f
Revises: 5eb531f8b167
Create Date: 2025-12-15 04:25:22.320988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cce9839893f'
down_revision: Union[str, Sequence[str], None] = '5eb531f8b167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("warnings", sa.Integer(), server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'warnings')
    # ### end Alembic commands ###
