"""ban users

Revision ID: 5eb531f8b167
Revises: 3cbdb33467f0
Create Date: 2025-12-14 04:48:33.417393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb531f8b167'
down_revision: Union[str, Sequence[str], None] = '3cbdb33467f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('ban_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'banned')
    # ### end Alembic commands ###
