"""add admin_log table

Revision ID: e060b471efb4
Revises: 44425c1c7ccd
Create Date: 2025-11-28 02:10:30.008351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e060b471efb4'
down_revision: Union[str, Sequence[str], None] = '44425c1c7ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_tg_id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_log')
    # ### end Alembic commands ###
